# Generated by Django 5.1.7 on 2025-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('apoint', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('status_box', models.BooleanField(default=False)),
            ],
        ),
    ]
