# Generated by Django 5.1.7 on 2025-03-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='due_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='task_date',
            new_name='start_date',
        ),
    ]
