# Generated by Django 5.1.7 on 2025-03-13 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_due_date_todo_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='status_box',
            new_name='status',
        ),
    ]
