# Generated by Django 5.1.7 on 2025-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_rename_status_box_todo_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='apoint',
            new_name='assigned',
        ),
    ]
