# Generated by Django 5.1.7 on 2025-03-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_rename_apoint_todo_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='assigned',
            field=models.CharField(blank=True, choices=[('Anuj', 'Anuj'), ('Sourav', 'Sourav')], max_length=100),
        ),
    ]
