# Generated by Django 5.1.7 on 2025-03-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_alter_todo_assigned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'verbose_name_plural': '1. Todo'},
        ),
    ]
