# Generated by Django 5.1.7 on 2025-03-13 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('assigned', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('check_box', models.BooleanField(default=False)),
            ],
        ),
    ]
